"""add okf record table"""

revision = '950c0ebaeb65'
down_revision = '20260628_000003'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('okf_records',
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['uploaded_documents.id'], name=op.f('fk_okf_records_source_document_id_uploaded_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_okf_records'))
    )
    op.create_index(op.f('ix_okf_records_source_document_id'), 'okf_records', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_okf_records_title'), 'okf_records', ['title'], unique=False)
    op.create_index(op.f('ix_okf_records_type'), 'okf_records', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_okf_records_type'), table_name='okf_records')
    op.drop_index(op.f('ix_okf_records_title'), table_name='okf_records')
    op.drop_index(op.f('ix_okf_records_source_document_id'), table_name='okf_records')
    op.drop_table('okf_records')
    # ### end Alembic commands ###

