from __future__ import annotations

import contextvars
import logging
from typing import Any

from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent

from app.agents.tools import (
    answer_general_knowledge,
    export_notes,
    flashcard_generator,
    keyword_search,
    quiz_generator,
    search_documents,
    summarize_document,
)
from app.core.config import settings

logger = logging.getLogger(__name__)

# ContextVar for user_id (async-safe, isolated per request/task)
_current_user_id: contextvars.ContextVar[str | None] = contextvars.ContextVar('current_user_id', default=None)


def get_agent_llm() -> ChatOpenAI:
    """Initialize ChatOpenAI LLM instance based on existing application configuration."""
    provider = settings.LLM_PROVIDER.lower() if settings.LLM_PROVIDER else "ollama"

    if settings.USE_OPENAI or provider == "openai":
        return ChatOpenAI(
            api_key=settings.OPENAI_API_KEY,
            model=settings.OPENAI_MODEL_NAME or settings.DEFAULT_CHAT_MODEL,
            temperature=0,
        )
    elif provider == "groq":
        return ChatOpenAI(
            api_key=settings.GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1",
            model=settings.GROQ_MODEL,
            temperature=0,
        )
    else:
        # Default to local Ollama via OpenAI-compatible endpoint
        base_url = f"{settings.OLLAMA_BASE_URL.rstrip('/')}/v1"
        return ChatOpenAI(
            api_key="ollama",
            base_url=base_url,
            model=settings.DEFAULT_CHAT_MODEL,
            temperature=0,
        )


def build_router_agent():
    """Create and return a compiled LangGraph ReAct agent with tools."""
    llm = get_agent_llm()
    tools = [
        search_documents,
        summarize_document,
        answer_general_knowledge,
        keyword_search,
        flashcard_generator,
        quiz_generator,
        export_notes,
    ]
    return create_react_agent(llm, tools)


def run_agent(user_query: str, user_id: str | None = None) -> dict[str, Any]:
    """Execute the router agent for a user query and return the answer and called tools.

    Args:
        user_query: The query string from the user.
        user_id: The user ID string to scope tool operations. Required for multi-user isolation.

    Returns:
        A dictionary with keys:
            - 'answer': str (final text answer generated by the agent)
            - 'tools_called': list[str] (names of tools invoked during processing)
            - 'raw_messages': list (full conversation messages output)
    """
    # Set user_id in ContextVar for tools to access (async-safe, isolated per request/task)
    import time
    request_start = time.time()
    timestamp = time.strftime('%H:%M:%S', time.localtime(request_start))
    print(f"[run_agent] {timestamp} Request START for user_id: {user_id}")
    logger.info(f"[run_agent] {timestamp} Request START for user_id: {user_id}")
    token = _current_user_id.set(user_id)
    print(f"[run_agent] {timestamp} ContextVar SET for user_id: {user_id}")
    logger.info(f"[run_agent] {timestamp} ContextVar SET for user_id: {user_id}")
    
    try:
        agent = build_router_agent()
        # Pass user_id in configurable for tools to access via RunnableConfig
        config = {"configurable": {"user_id": user_id}} if user_id else {}
        print(f"[run_agent] Building config with user_id: {user_id}, config dict: {config}")
        logger.info(f"[run_agent] Building config with user_id: {user_id}, config dict: {config}")
        result = agent.invoke({"messages": [("user", user_query)]}, config=config)
        messages = result.get("messages", [])

        tools_called: list[str] = []
        final_answer: str = ""

        for msg in messages:
            # Capture tools requested in tool_calls
            if hasattr(msg, "tool_calls") and msg.tool_calls:
                for tc in msg.tool_calls:
                    name = tc.get("name") if isinstance(tc, dict) else getattr(tc, "name", None)
                    if name and name not in tools_called:
                        tools_called.append(name)

            # Capture tool output message names
            if getattr(msg, "type", "") == "tool" or msg.__class__.__name__ == "ToolMessage":
                name = getattr(msg, "name", None)
                if name and name not in tools_called:
                    tools_called.append(name)

            # Capture final AI text response
            if getattr(msg, "type", "") == "ai" or msg.__class__.__name__ == "AIMessage":
                if hasattr(msg, "content") and msg.content:
                    if isinstance(msg.content, str):
                        final_answer = msg.content
                    elif isinstance(msg.content, list):
                        text_parts = [
                            item.get("text", "") if isinstance(item, dict) else str(item)
                            for item in msg.content
                        ]
                        final_answer = "".join(text_parts)

        return {
            "answer": final_answer,
            "tools_called": tools_called,
            "raw_messages": messages,
        }
    finally:
        # Reset ContextVar to prevent cross-request contamination
        timestamp = time.strftime('%H:%M:%S', time.localtime(time.time()))
        print(f"[run_agent] {timestamp} ContextVar RESET for user_id: {user_id}")
        logger.info(f"[run_agent] {timestamp} ContextVar RESET for user_id: {user_id}")
        _current_user_id.reset(token)
        elapsed = time.time() - request_start
        timestamp = time.strftime('%H:%M:%S', time.localtime(time.time()))
        print(f"[run_agent] {timestamp} Request END for user_id: {user_id} (elapsed: {elapsed:.3f}s)")
        logger.info(f"[run_agent] {timestamp} Request END for user_id: {user_id} (elapsed: {elapsed:.3f}s)")
